resources:
  repositories:
    - repository: self
      checkoutOptions:
        submodules: true
        lfs: true
    - repository: templates
      type: github
      name: kritikos-io/.config
      endpoint: kritikos-io

trigger:
  batch: true
  branches:
    include:
      - master
      - develop
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - azure-pipelines.yml
      - src/*
      - tests/*

variables:
  - group: Environment
  - group: DotNet
  - group: ApiKeys
  - name: SONAR_PROJECT
    value: kritikos-io_DevOps.Tools

stages:
  - template: /ci/azure-pipelines/stages/general/00. gitversion.yml@templates
    parameters:
      updateAssemblyInfo: true
  - template: /ci/azure-pipelines/stages/dotnet/00. build.yml@templates
    parameters:
      useCache: true
      configuration: Release
      updateAssemblyInfo: true
      publishWeb: false
      buildOnLinux: true
      buildOnWindows: true
      packOnLinux: true
  - template: /ci/azure-pipelines/stages/dotnet/01. test.yml@templates
    parameters:
      useCache: true
      configuration: Debug
      testOnLinux: true
      testOnWindows: true
      coverageOnLinux: true
      sonarOnLinux: true
      codecovOnLinux: true
      coverallsOnLinux: true
  - template: /ci/azure-pipelines/stages/dotnet/02. nuget-deploy.yml@templates
    parameters:
      dependsOn:
        - Build
        - Test
      packagesToPush: $(Pipeline.Workspace)/nuget/*.nupkg
      artifact: nuget
      environment-pr: Pull Requests
      environment-release: Release
      feedName-pr: Kritikos
      feedName-release: Kritikos
