resources:
  repositories:
    - repository: self
      checkoutOptions:
        submodules: true
        lfs: true
    - repository: templates
      type: github
      name: kritikos-io/.config
      endpoint: kritikos-io

trigger:
  batch: true
  branches:
    include:
      - master
      - develop
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - azure-pipelines.yml
      - src/*
      - tests/*

stages:
  - template: /ci/azure-pipelines/stages/general/00. gitversion.yml@templates
    parameters:
      updateAssemblyInfo: true
  - template: /ci/azure-pipelines/stages/dotnet/00. build.yml@templates
    parameters:
      useCache: false
      updateAssemblyInfo: true
      publishWeb: false
      buildOnLinux: true
      packOnLinux: true
